# Site settings
title: Engineering at Monsanto
name: Engineering at Monsanto
header-img: img/mon-field_rows.jpg
email: engineering@Monsanto.com
description: "The engineers of Monsanto produce code that powers agricultural products that support farmers all around the world. Our goal of sustainable agriculture mirrors the way we present our ideas and code to the world."
baseurl: ""
url: "http://engineering.monsanto.com"
twitter_username: MonPlatformEng
youtube_username: MonsantoCo
github_username:  MonsantoCo
facebook_username: MonsantoCo

# Build settings
#markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: ["autolink", "no_intra_emphasis", "smart", "tables"]
fenced_code_blocks: true
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","update_prod.sh"]

# Sitemap
sitemap:
    #file: "/sitemap.xml"
    file: "/feed.xml"
    exclude:
       - "/rss.xml"
       - "/atom.xml"
       - "/feed.xml"
       - "/feed/index.xml"
    include_posts:
       - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"#

